version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - aws ec2 run-instances --region us-west-1 --image-id ami-04ceee5659211731a
      #- mvn install 
      #- echo $CICD
  post_build:
    commands:
      - echo Build completed on `date`
# artifacts:
  # files:
    # - target/messageUtil-1.0.jar
